declare type ColorData = number[];
export declare class Color {
    private _data;
    static fromArray(vals: ColorData, base256?: boolean): Color;
    static fromString(css: string): Color;
    static fromNumber(val: number, base256?: boolean): Color;
    constructor(r?: number, g?: number, b?: number, rand?: number, redRand?: number, greenRand?: number, blueRand?: number);
    private get _r();
    private set _r(value);
    private get _g();
    private set _g(value);
    private get _b();
    private set _b(value);
    private get _rand();
    private get _redRand();
    private get _greenRand();
    private get _blueRand();
    equals(other: Color | ColorData): boolean;
    copy(other: Color | ColorData): this;
    clone(): Color;
    set(_r?: number, _g?: number, _b?: number, _rand?: number, _redRand?: number, _greenRand?: number, _blueRand?: number): this;
    clear(): this;
    toInt(base256?: boolean): number;
    fromInt(val: number, base256?: boolean): this;
    clamp(): this;
    mix(other: Color | ColorData, percent: number): this;
    lighten(percent: number): this;
    darken(percent: number): this;
    bake(): void;
    add(other: Color | ColorData, percent?: number): this;
    scale(percent: number): this;
    multiply(other: Color | ColorData): this;
    toString(base256?: boolean): string;
}
export declare function make(arg: ColorData | string | number, base256?: boolean): Color;
export {};
